name: Unity CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*' # Ignoruj wszystkie zmiany domyślnie
    # Sprawdzaj, czy wiadomość commita zaczyna się od [RELEASE]
    condition: startsWith(github.event.head_commit.message, '[RELEASE]')
  pull_request:

jobs:
  test:
    name: Run Unity Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Cache Library Folder
        uses: actions/cache@v4.1.2
        with:
          path: Library
          key: ${{ runner.os }}-library-${{ hashFiles('**/ProjectSettings/ProjectVersion.txt') }}
          restore-keys: |
            ${{ runner.os }}-library-

      - name: Run tests
        uses: game-ci/unity-test-runner@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: .
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Test Results
        uses: actions/upload-artifact@v4.4.3
        if: always()
        with:
          name: Test Results
          path: Artifacts/TestResults.xml

  build:
    strategy:
      matrix:
        target_platform: ["StandaloneWindows64", "StandaloneLinux64", "StandaloneOSX"]
    name: Build Unity Project for ${{ matrix.target_platform }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: Cache Library
        uses: actions/cache@v4.1.2
        with:
          path: Library
          key: ${{ runner.os }}-unity-${{ hashFiles('**/ProjectSettings/ProjectVersion.txt') }}
          restore-keys: |
            ${{ runner.os }}-unity-

      - name: Build Project
        uses: game-ci/unity-builder@v4.3.0
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.target_platform }}

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4.4.3
        if: ${{ matrix.target_platform != 'StandaloneLinux64' }} # Tymczasowo ignoruje wersje na Linuxa, żeby oszczędzić miejce
        with:
          name: Build-${{ matrix.target_platform }}
          path: build

  release:
    needs: build
    name: Deploy a release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4.1.8
        with:
          path: ${{ github.workspace}}/release

      - name: Zip release
        run: |
          mv ${{ github.workspace}}/release/Build-StandaloneWindows64/* .
          zip -r Build-StandaloneWindows64.zip StandaloneWindows64
          mv ${{ github.workspace}}/release/Build-StandaloneOSX/* .
          zip -r Build-StandaloneOSX.zip StandaloneOSX

      - name: Release
        uses: softprops/action-gh-release@v2.1.0
        with:
          tag_name: latest
          files: |
            Build-StandaloneWindows64.zip
            Build-StandaloneOSX.zip
